### ISSUE TITLE
feat: Configure Token Symbols and Support Price Conversion

### ISSUE THREAD

**Issue by gluckzhang** [Firstset/tenderduty#27]
Related to #24, we need a way to display token symbols for each chain and convert the tokens to a fiat currency. The plan is to use CoinMarketCap API and cache the data for several hours in memory. There should be new fields in a config yaml file, here using Babylon as an example:

```yaml
coin_market_cap_api_token: xxxxxx
convert_to_fiat:
  enable: true
  currency: USD # or EUR, etc.
chains:
  "babylon-mainnet":
    symbol: BABY
```
